# Generated by Django 2.2.1 on 2019-05-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Yurii', max_length=255),
            preserve_default=False,
        ),
    ]
