version: "3"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6380:6379

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./music_hub:/music_hub
    command: sh -c "python manage.py wait_for_db && python manage.py migrate  &&
      python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
    command: celery -A music_hub worker -l info
    env_file: .env
    depends_on:
      - db
      - redis

