# Generated by Django 2.2.1 on 2019-05-25 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribers',
            unique_together={('subscriber', 'user')},
        ),
    ]
