# Generated by Django 2.2.1 on 2019-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20190519_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
