version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORDlatest: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    ports:
      - 6380:6379
